x = input('Digite algo: ')
print(f'Você escreveu {x}')
print('Você escreveu o tipo', type(x))
print('É um numero?', x.isnumeric())
print('São letras?', x.isalpha())
print('É um digito?', x.isdigit())
print('É tudo numero?',x.isalnum())
print('É imprimivel?',x.isprintable())
print('É só em letras minusculas?', x.isupper())
print('fim')
